import type { NodeDefinition } from '../../types.js';

export const githubNode: NodeDefinition = {
  id: 'github.mcp',
  label: 'GitHub',
  name: 'GitHub',
  category: 'Tools',
  variant: 'connector',
  description: 'Complete GitHub integration - manage repos, issues, PRs, commits, branches, and more.',
  icon: '/iconSvg/github.svg',
  color: '#24292e',
  executionKey: 'github_mcp',
  usableAsTool: true,
  inputs: [{ name: 'input', type: 'data', position: 'left' }],
  outputs: [{ name: 'output', type: 'any', position: 'right' }],
  isTrigger: false,
  bg: 'bg-[#24292e]/10',
  border: 'border-[#24292e]/20',
  credentialTypes: ['github_pat', 'github_oauth'],
  configFields: [
    { key: 'auth_notice', label: 'Note: Ensure your PAT has "repo" and "workflow" scopes.', type: 'notice' },
    { key: 'resource', label: 'Resource Type', type: 'select',
      options: ['repository', 'issue', 'pullRequest', 'commit', 'branch', 'comment'],
      default: 'repository' },
    { key: 'operation', label: 'Operation', type: 'select',
      options: ['listUserRepos', 'listOrgRepos', 'listRepos', 'getRepo', 'createRepo', 'deleteRepo', 'listIssues', 'getIssue', 'createIssue', 'updateIssue', 'listPullRequests', 'getPullRequest', 'createPullRequest', 'updatePullRequest', 'mergePullRequest', 'listCommits', 'getCommit', 'listBranches', 'getBranch', 'listComments', 'createComment', 'deleteComment'],
      default: 'listUserRepos' },
  ],
  operationInputs: {
    listUserRepos: [
      { key: 'owner', label: 'Username', type: 'string', required: true, description: 'GitHub username to find repos for', example: 'torvalds' },
    ],
    listOrgRepos: [
      { key: 'owner', label: 'Organization', type: 'string', required: true, description: 'GitHub organization', example: 'microsoft' },
    ],
    listRepos: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
    ],
    getRepo: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
    ],
    createRepo: [
      { key: 'name', label: 'Repository Name', type: 'string', required: true, description: 'Name for new repo', example: 'my-awesome-project' },
      { key: 'description', label: 'Description', type: 'string', required: false, description: 'Repository description', example: 'An awesome project' },
      { key: 'private', label: 'Private', type: 'string', required: false, description: 'true or false', example: 'false' },
    ],
    deleteRepo: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
    ],
    listIssues: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
      { key: 'state', label: 'State', type: 'string', required: false, description: 'open, closed, or all', example: 'open' },
    ],
    getIssue: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
      { key: 'issueNumber', label: 'Issue Number', type: 'string', required: true, description: 'Issue number', example: '123' },
    ],
    createIssue: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
      { key: 'title', label: 'Title', type: 'string', required: true, description: 'Issue title', example: 'Bug: Application crashes' },
      { key: 'body', label: 'Description', type: 'string', required: false, description: 'Issue description', example: 'Steps to reproduce...' },
      { key: 'assignees', label: 'Assignees', type: 'string', required: false, description: 'Comma-separated usernames', example: 'octocat,hubot' },
      { key: 'milestone', label: 'Milestone', type: 'string', required: false, description: 'Milestone ID or number', example: '1' },
      { key: 'labels', label: 'Labels', type: 'string', required: false, description: 'Comma-separated labels', example: 'bug,urgent' },
    ],
    updateIssue: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
      { key: 'issueNumber', label: 'Issue Number', type: 'string', required: true, description: 'Issue number', example: '123' },
      { key: 'state', label: 'State', type: 'string', required: false, description: 'open or closed', example: 'closed' },
      { key: 'title', label: 'Title', type: 'string', required: false, description: 'New title', example: 'Updated: Application crashes' },
      { key: 'body', label: 'Description', type: 'string', required: false, description: 'Updated description', example: 'New steps...' },
      { key: 'assignees', label: 'Assignees', type: 'string', required: false, description: 'Comma-separated usernames', example: 'octocat' },
    ],
    closeIssue: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
      { key: 'issueNumber', label: 'Issue Number', type: 'string', required: true, description: 'Issue number', example: '123' },
    ],
    reopenIssue: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
      { key: 'issueNumber', label: 'Issue Number', type: 'string', required: true, description: 'Issue number', example: '123' },
    ],
    addLabel: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
      { key: 'issueNumber', label: 'Issue Number', type: 'string', required: true, description: 'Issue number', example: '123' },
      { key: 'labels', label: 'Labels', type: 'string', required: true, description: 'Comma-separated labels to add', example: 'bug,feature' },
    ],
    removeLabel: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
      { key: 'issueNumber', label: 'Issue Number', type: 'string', required: true, description: 'Issue number', example: '123' },
      { key: 'labels', label: 'Labels', type: 'string', required: true, description: 'Labels to remove', example: 'wontfix' },
    ],
    listPullRequests: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
      { key: 'state', label: 'State', type: 'string', required: false, description: 'open, closed, or all', example: 'open' },
    ],
    getPullRequest: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
      { key: 'prNumber', label: 'PR Number', type: 'string', required: true, description: 'Pull request number', example: '123' },
    ],
    createPullRequest: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
      { key: 'title', label: 'Title', type: 'string', required: true, description: 'PR title', example: 'Add new feature' },
      { key: 'head', label: 'Head Branch', type: 'string', required: true, description: 'Source branch', example: 'feature/new-feature' },
      { key: 'base', label: 'Base Branch', type: 'string', required: true, description: 'Target branch', example: 'main' },
      { key: 'body', label: 'Description', type: 'string', required: false, description: 'PR description', example: 'Fixes issue #123' },
    ],
    updatePullRequest: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
      { key: 'prNumber', label: 'PR Number', type: 'string', required: true, description: 'Pull request number', example: '123' },
      { key: 'state', label: 'State', type: 'string', required: false, description: 'open or closed', example: 'closed' },
      { key: 'title', label: 'Title', type: 'string', required: false, description: 'New title', example: 'Updated PR title' },
      { key: 'body', label: 'Description', type: 'string', required: false, description: 'Updated description', example: 'Updated details...' },
    ],
    mergePullRequest: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
      { key: 'prNumber', label: 'PR Number', type: 'string', required: true, description: 'Pull request number', example: '123' },
      { key: 'mergeMethod', label: 'Merge Method', type: 'string', required: false, description: 'merge, squash, or rebase', example: 'merge' },
    ],
    listCommits: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
      { key: 'branch', label: 'Branch', type: 'string', required: false, description: 'Branch name (default: main)', example: 'main' },
    ],
    getCommit: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
      { key: 'sha', label: 'Commit SHA', type: 'string', required: true, description: 'Commit SHA hash', example: 'abc123def456' },
    ],
    listBranches: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
    ],
    createBranch: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
      { key: 'branchName', label: 'Branch Name', type: 'string', required: true, description: 'New branch name', example: 'feature/new-feature' },
      { key: 'fromBranch', label: 'From Branch', type: 'string', required: false, description: 'Source branch (default: main)', example: 'main' },
    ],
    deleteBranch: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
      { key: 'branchName', label: 'Branch Name', type: 'string', required: true, description: 'Branch to delete', example: 'feature/old-feature' },
    ],
    listComments: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
      { key: 'issueNumber', label: 'Issue Number', type: 'string', required: true, description: 'Issue or PR number', example: '123' },
    ],
    createComment: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
      { key: 'issueNumber', label: 'Issue Number', type: 'string', required: true, description: 'Issue or PR number', example: '123' },
      { key: 'body', label: 'Comment', type: 'string', required: true, description: 'Comment text', example: 'Great work!' },
    ],
    updateComment: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
      { key: 'commentId', label: 'Comment ID', type: 'string', required: true, description: 'Comment ID', example: '123456' },
      { key: 'body', label: 'Comment', type: 'string', required: true, description: 'Updated comment text', example: 'Updated comment' },
    ],
    deleteComment: [
      { key: 'owner', label: 'Owner', type: 'string', required: true, description: 'Repository owner', example: 'microsoft' },
      { key: 'repo', label: 'Repository', type: 'string', required: true, description: 'Repository name', example: 'vscode' },
      { key: 'commentId', label: 'Comment ID', type: 'string', required: true, description: 'Comment ID', example: '123456' },
    ],
  },
  operationOutputs: {
    listUserRepos: [
      { key: 'status', type: 'string' },
      { key: 'data[0].id', type: 'number' },
      { key: 'data[0].name', type: 'string' },
      { key: 'data[0].full_name', type: 'string' },
      { key: 'data[0].html_url', type: 'string' },
      { key: 'data[0].description', type: 'string' },
    ],
    listOrgRepos: [
      { key: 'status', type: 'string' },
      { key: 'data[0].id', type: 'number' },
      { key: 'data[0].name', type: 'string' },
      { key: 'data[0].html_url', type: 'string' },
    ],
    listRepos: [
      { key: 'status', type: 'string' },
      { key: 'data[0].id', type: 'number' },
      { key: 'data[0].name', type: 'string' },
      { key: 'data[0].html_url', type: 'string' },
    ],
    getRepo: [
      { key: 'status', type: 'string' },
      { key: 'data.id', type: 'number' },
      { key: 'data.name', type: 'string' },
      { key: 'data.full_name', type: 'string' },
      { key: 'data.html_url', type: 'string' },
      { key: 'data.description', type: 'string' },
    ],
    createRepo: [
      { key: 'status', type: 'string' },
      { key: 'data.id', type: 'number' },
      { key: 'data.name', type: 'string' },
      { key: 'data.html_url', type: 'string' },
    ],
    deleteRepo: [
      { key: 'status', type: 'string' },
    ],
    listIssues: [
      { key: 'status', type: 'string' },
      { key: 'data[0].id', type: 'number' },
      { key: 'data[0].number', type: 'number' },
      { key: 'data[0].title', type: 'string' },
      { key: 'data[0].body', type: 'string' },
      { key: 'data[0].state', type: 'string' },
      { key: 'data[0].user.login', type: 'string' },
      { key: 'data[0].html_url', type: 'string' },
    ],
    getIssue: [
      { key: 'status', type: 'string' },
      { key: 'data.id', type: 'number' },
      { key: 'data.number', type: 'number' },
      { key: 'data.title', type: 'string' },
      { key: 'data.body', type: 'string' },
      { key: 'data.state', type: 'string' },
      { key: 'data.html_url', type: 'string' },
    ],
    createIssue: [
      { key: 'status', type: 'string' },
      { key: 'data.id', type: 'number' },
      { key: 'data.number', type: 'number' },
      { key: 'data.title', type: 'string' },
      { key: 'data.html_url', type: 'string' },
    ],
    updateIssue: [
      { key: 'status', type: 'string' },
      { key: 'data.id', type: 'number' },
      { key: 'data.number', type: 'number' },
      { key: 'data.state', type: 'string' },
    ],
    listPullRequests: [
      { key: 'status', type: 'string' },
      { key: 'data[0].id', type: 'number' },
      { key: 'data[0].number', type: 'number' },
      { key: 'data[0].title', type: 'string' },
      { key: 'data[0].state', type: 'string' },
      { key: 'data[0].html_url', type: 'string' },
    ],
    getPullRequest: [
      { key: 'status', type: 'string' },
      { key: 'data.id', type: 'number' },
      { key: 'data.number', type: 'number' },
      { key: 'data.title', type: 'string' },
      { key: 'data.html_url', type: 'string' },
    ],
    createPullRequest: [
      { key: 'status', type: 'string' },
      { key: 'data.id', type: 'number' },
      { key: 'data.number', type: 'number' },
      { key: 'data.html_url', type: 'string' },
    ],
    mergePullRequest: [
      { key: 'status', type: 'string' },
      { key: 'data.sha', type: 'string' },
      { key: 'data.merged', type: 'boolean' },
      { key: 'data.message', type: 'string' },
    ],
    listCommits: [
      { key: 'status', type: 'string' },
      { key: 'data[0].sha', type: 'string' },
      { key: 'data[0].commit.message', type: 'string' },
      { key: 'data[0].commit.author.name', type: 'string' },
      { key: 'data[0].html_url', type: 'string' },
    ],
    getCommit: [
      { key: 'status', type: 'string' },
      { key: 'data.sha', type: 'string' },
      { key: 'data.commit.message', type: 'string' },
    ],
    listBranches: [
      { key: 'status', type: 'string' },
      { key: 'data[0].name', type: 'string' },
      { key: 'data[0].commit.sha', type: 'string' },
    ],
    createBranch: [
      { key: 'status', type: 'string' },
      { key: 'data.ref', type: 'string' },
      { key: 'data.object.sha', type: 'string' },
    ],
    deleteBranch: [
      { key: 'status', type: 'string' },
    ],
    listComments: [
      { key: 'status', type: 'string' },
      { key: 'data[0].id', type: 'number' },
      { key: 'data[0].body', type: 'string' },
      { key: 'data[0].user.login', type: 'string' },
    ],
    createComment: [
      { key: 'status', type: 'string' },
      { key: 'data.id', type: 'number' },
      { key: 'data.body', type: 'string' },
      { key: 'data.html_url', type: 'string' },
    ],
    deleteComment: [
      { key: 'status', type: 'string' },
    ],
  },
  requiredInputs: [
    {
      key: 'operation',
      label: 'Operation',
      type: 'string',
      required: true,
      description: 'GitHub operation to perform',
      example: 'listUserRepos',
    },
  ],
  outputSchema: [
    { key: 'status', type: 'string', description: 'Operation status', example: 'success' },
    { key: 'data', type: 'any', description: 'Raw GitHub API response data', example: {} },
  ],
};
