import type { NodeDefinition } from '../types';

export const dataNodes: NodeDefinition[] = [
  {
    id: 'database.mongodb',
    label: 'MongoDB',
    name: 'MongoDB Atlas',
    description: 'Interact with MongoDB Atlas cluster.',
    category: 'Databases',
    variant: 'connector',
    icon: '/iconSvg/mongodb-icon.svg',
    color: 'text-green-500',
    bg: 'bg-green-500/10',
    border: 'border-green-500/20',
    isTrigger: false,
    executionKey: 'mongodb_atlas',
    credentialTypes: ['mongodb_atlas'],
    inputs: [{ name: 'input', type: 'data' }],
    outputs: [{ name: 'output', type: 'memory', color: '#a855f7' }],
    configFields: [
      { key: 'collection', label: 'Collection', type: 'text', placeholder: 'users', default: 'users' },
      {
        key: 'operation',
        label: 'Operation',
        type: 'select',
        options: [
          { label: 'Insert One', value: 'insertOne' },
          { label: 'Find One', value: 'findOne' },
          { label: 'Find Many', value: 'findMany' },
          { label: 'Update One', value: 'updateOne' },
          { label: 'Delete One', value: 'deleteOne' },
          { label: 'Upsert (Update or Insert)', value: 'upsert' },
          { label: 'Create Collection (Table)', value: 'createCollection' },
          { label: 'List Collections (Tables)', value: 'listCollections' },
          { label: 'Count Documents', value: 'count' },
        ],
        default: 'insertOne',
      },
      {
        key: 'document',
        label: 'Document / Filter',
        type: 'textarea',
        placeholder: '{"email": "{input.email}"}',
        displayOptions: { showFor: { operation: ['insertOne', 'findOne', 'updateOne', 'deleteOne', 'upsert'] } },
      },
      {
        key: 'query',
        label: 'Query Filter',
        type: 'textarea',
        placeholder: '{"status": "active"}',
        displayOptions: { showFor: { operation: ['findMany', 'updateOne', 'upsert', 'count'] } },
      },
    ],
  },
  {
    id: 'database.redis',
    label: 'Redis',
    name: 'Redis Database',
    description: 'Interact with Redis key-value store.',
    category: 'Databases',
    variant: 'connector',
    icon: '/iconSvg/redis.svg',
    color: 'text-red-500',
    bg: 'bg-red-500/10',
    border: 'border-red-500/20',
    isTrigger: false,
    executionKey: 'redis',
    credentialTypes: ['redis'],
    inputs: [{ name: 'input', type: 'data' }],
    outputs: [{ name: 'output', type: 'memory', color: '#a855f7' }],
    configFields: [
      {
        key: 'operation',
        label: 'Operation',
        type: 'select',
        options: [
          { label: 'Get', value: 'get' },
          { label: 'Set', value: 'set' },
          { label: 'Delete', value: 'del' },
          { label: 'Increment', value: 'incr' },
          { label: 'Hash Set (Object)', value: 'hset' },
          { label: 'Hash Get (Object)', value: 'hget' },
          { label: 'List Push (Append)', value: 'lpush' },
          { label: 'List Range (Get All)', value: 'lrange' },
        ],
        default: 'get',
      },
      { key: 'key', label: 'Key', type: 'text', placeholder: 'user:{input.id}' },
      {
        key: 'value',
        label: 'Value',
        type: 'textarea',
        placeholder: '{"field": "value"} or just "string"',
        displayOptions: { showFor: { operation: ['set', 'hset', 'lpush'] } },
      },
      {
        key: 'ttl',
        label: 'TTL (Seconds)',
        type: 'text',
        placeholder: '3600',
        displayOptions: { showFor: { operation: ['set'] } },
      },
    ],
  },
];
