import type { NodeDefinition } from '../types';

export const modelNodes: NodeDefinition[] = [
  {
    id: 'model.openai',
    label: 'OpenAI',
    name: 'OpenAI',
    category: 'Models',
    variant: 'connector',
    description: 'Connect OpenAI GPT models.',
    icon: '/iconSvg/openai.svg',
    color: '#10a37f',
    bg: 'bg-[#10a37f]/10',
    border: 'border-[#10a37f]/20',
    isTrigger: false,
    executionKey: 'config_model',
    inputs: [{ name: 'input', type: 'data', position: 'left' }],
    outputs: [{ name: 'model', type: 'model', position: 'top' }],
    configFields: [
      {
        key: 'model',
        label: 'Model Name',
        type: 'select',
        options: ['gpt-4o', 'gpt-4o-mini', 'gpt-3.5-turbo'],
        placeholder: 'Select a model',
      },
      { key: 'temperature', label: 'Temperature (0-1)', type: 'text', placeholder: '0.7' },
      { key: 'maxTokens', label: 'Max Tokens', type: 'text', placeholder: '4096' },
    ],
    credentialTypes: ['openai_api_key'],
  },
  {
    id: 'model.gemini',
    label: 'Gemini',
    name: 'Gemini',
    category: 'Models',
    variant: 'connector',
    description: 'Connect Google Gemini models.',
    icon: '/iconSvg/gemini-color.svg',
    color: '#4285f4',
    bg: 'bg-[#4285f4]/10',
    border: 'border-[#4285f4]/20',
    isTrigger: false,
    executionKey: 'config_model',
    inputs: [{ name: 'input', type: 'data', position: 'left' }],
    outputs: [{ name: 'model', type: 'model', position: 'top' }],
    configFields: [
      {
        key: 'model',
        label: 'Model Name',
        type: 'select',
        options: ['gemini-2.0-flash-001', 'gemini-1.5-pro', 'gemini-1.5-flash'],
        placeholder: 'Select a model',
      },
      { key: 'temperature', label: 'Temperature (0-1)', type: 'text', placeholder: '0.7' },
      { key: 'maxTokens', label: 'Max Tokens', type: 'text', placeholder: '4096' },
    ],
    credentialTypes: ['google_api_key'],
  },
  {
    id: 'model.claude',
    label: 'Claude',
    name: 'Claude',
    category: 'Models',
    variant: 'connector',
    description: 'Connect Anthropic Claude models.',
    icon: '/iconSvg/claude-color.svg',
    color: '#d97706',
    bg: 'bg-[#d97706]/10',
    border: 'border-[#d97706]/20',
    isTrigger: false,
    executionKey: 'config_model',
    inputs: [{ name: 'input', type: 'data', position: 'left' }],
    outputs: [{ name: 'model', type: 'model', position: 'top' }],
    configFields: [
      {
        key: 'model',
        label: 'Model Name',
        type: 'select',
        options: ['claude-3-5-sonnet-20240620', 'claude-3-opus-20240229', 'claude-3-haiku-20240307'],
        placeholder: 'Select a model',
      },
      { key: 'temperature', label: 'Temperature (0-1)', type: 'text', placeholder: '0.7' },
      { key: 'maxTokens', label: 'Max Tokens', type: 'text', placeholder: '4096' },
    ],
    credentialTypes: ['anthropic_api_key'],
  },
  {
    id: 'model.openrouter',
    label: 'OpenRouter',
    name: 'OpenRouter',
    category: 'Models',
    variant: 'connector',
    description: 'Connect any model via OpenRouter.',
    icon: '/iconSvg/openrouter.svg',
    color: '#7c3aed',
    bg: 'bg-[#7c3aed]/10',
    border: 'border-[#7c3aed]/20',
    isTrigger: false,
    executionKey: 'config_model',
    inputs: [{ name: 'input', type: 'data', position: 'left' }],
    outputs: [{ name: 'model', type: 'model', position: 'top' }],
    configFields: [
      {
        key: 'model',
        label: 'Model ID (OpenRouter)',
        type: 'select',
        options: ['openai/gpt-4o', 'anthropic/claude-3.5-sonnet', 'google/gemini-pro-1.5'],
        placeholder: 'Select or enter model ID',
      },
    ],
    credentialTypes: ['openrouter_api_key'],
  },
];
