import type { NodeDefinition } from '../types';

export const triggers: NodeDefinition[] = [
  {
    id: 'trigger.manual',
    label: "When clicking 'Execute workflow'",
    name: 'Manual Start',
    category: 'Triggers',
    variant: 'trigger',
    description: 'Trigger the workflow manually via the Run button.',
    icon: 'MousePointer2',
    color: '#94a3b8',
    bg: 'bg-[#1e1e1e]',
    border: 'border-zinc-700',
    isTrigger: true,
    executionKey: 'trigger_manual',
    inputs: [],
    outputs: [{ name: 'output', type: 'data', position: 'right' }],
    configFields: [],
  },
  {
    id: 'trigger.chat',
    label: 'When chat message received',
    name: 'Chat Trigger',
    category: 'Triggers',
    variant: 'trigger',
    description: 'Starts the workflow when a webchat message is submitted.',
    icon: 'MessageSquare',
    color: '#94a3b8',
    bg: 'bg-[#1e1e1e]',
    border: 'border-zinc-700',
    isTrigger: true,
    executionKey: 'trigger_chat',
    inputs: [],
    outputs: [{ name: 'output', type: 'data', position: 'right' }],
    configFields: [
      { key: 'test_input', label: 'Test Chat Message', type: 'chat_test' },
      {
        key: 'responseMode',
        label: 'Response Mode',
        type: 'select',
        options: ['When execution is finished', 'Immediately'],
        placeholder: 'When execution is finished',
      },
      { key: 'allowFileUploads', label: 'Allow File Uploads', type: 'boolean' },
    ],
  },
  {
    id: 'trigger.webhook',
    label: 'Webhook',
    name: 'Webhook',
    category: 'Triggers',
    variant: 'trigger',
    description: 'Listen for an incoming HTTP request to start the workflow.',
    icon: 'Webhook',
    color: '#0ea5e9',
    bg: 'bg-[#0ea5e9]/10',
    border: 'border-[#0ea5e9]/20',
    isTrigger: true,
    executionKey: 'trigger_webhook',
    inputs: [],
    outputs: [{ name: 'output', type: 'data', position: 'top' }],
    configFields: [
      { key: 'path', label: 'Webhook Path', type: 'text', placeholder: 'my-endpoint' },
      {
        key: 'httpMethod',
        label: 'HTTP Method',
        type: 'select',
        options: ['GET', 'POST'],
        placeholder: 'POST',
      },
      { key: 'responseCode', label: 'HTTP Response Code', type: 'text', placeholder: '200' },
      {
        key: 'responseData',
        label: 'HTTP Response Data',
        type: 'textarea',
        placeholder: '{"success": true}',
      },
    ],
  },
];
